[package]
name = "nn"
version = "0.1.0"
authors = ["Andrei Toterman <andrei.toterman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.14.0", features = ["rayon"] }
rand = "0.8.3"
